#! /bin/bash

is_verbose=false

#######################################################
# Functions available to be called from command-line
#######################################################

function diffy() {
    diff -y -W $(tput cols) "$1" "$2" | less
}


function get_current_git_branch() {
    local curr_git_branch=$(git branch --show-current 2>/dev/null)	
    if [ -n "${curr_git_branch}" ] ; then
        echo "[git:${curr_git_branch}]$"
    else
        echo ""
    fi
}


#######################################################
# Helper functions for this script
#######################################################

function check_if_verbose_requested() {
    local arg1="$1"
    local arg1_lower_case=""

    if [ -n "${arg1}" ] ; then
        arg1_lower_case="${arg1,,}"
    fi

    if [ "$arg1_lower_case" == "--verbose" ] || [ "$arg1_lower_case" == "-v" ] ; then
        is_verbose=true
    fi
}


function initialize() {
    local this_script_fullname="${BASH_SOURCE[0]}"
    local this_script_basename=$(basename ${this_script_fullname})
    local script_alias=$(echo ${this_script_basename} | tr -d .)

    echo "[+] Running ${this_script_fullname}"

    # Meta
    if [ "$is_verbose" == "true" ] ; then
        echo "[+] Declaring alias: ${script_alias}"
    fi

    alias ${script_alias}="vim ${this_script_fullname}; source ${this_script_fullname}"

}


function declare_alias_less() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Declaring alias: less
    fi

    alias less='less --quit-if-one-screen --ignore-case --LONG-PROMPT --LINE-NUMBERS --no-init'
}


function declare_git_friendly_PS1() {
    local ps1_has_git_prompt=$(echo ${PS1} | grep -o get_current_git_branch)

    if [ "$is_verbose" == "true" ] ; then
        if [ -z "${ps1_has_git_prompt}" ] ; then
            echo [+] Declaring git-friendly bash prompt declared
        else
            echo [-] Bash prompt is already git-friendly
        fi
    fi

    if [ -z "${ps1_has_git_prompt}" ] ; then
        local COLOR_LIGHTRED="\[\e[0;31m\]"
        local COLOR_STOP="\[\e[m\]"
        export PS1="${PS1}${COLOR_LIGHTRED}\$(get_current_git_branch)${COLOR_STOP} "
    fi
}


function customize_git() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Customizing git
    fi

    export GIT_EDITOR=vim
    alias gitgr="git log --color --graph --branches --all --decorate=short --oneline"
}


function customize_man() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Customizing man
    fi

    export MANPAGER='less --ignore-case --no-init'
}


function customize_ls() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Customizing ls
    fi

    export TIME_STYLE=long-iso
    alias ll='ls -l'
}


function customize_bash() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Customizing bash
    fi

    set -o noclobber
    shopt -s histverify
}


function customize_bash_history() {
    if [ "$is_verbose" == "true" ] ; then
        echo [+] Customizing bash history
    fi

    export HISTCONTROL=ignorespace
    export HISTSIZE=-1
    export HISTFILESIZE=-1
    export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "
}


function other_verbose_processing() {
    if [ "$is_verbose" == "true" ] ; then

        # Warn if .vimrc is missing 
        if [ -n "$(which vim)" ] && [ ! -e "${HOME}/.vimrc" ] ; then
            echo "[INFO] ~/.vimrc missing!"
        fi

        echo -n "[INFO] Current Shell Options: "
        echo "${SHELLOPTS//:/,}"

        echo -n "[INFO] Current Bash Options: "
        echo "${BASHOPTS//:/, }"
    fi
}


#######################################################
# Script begins here
#######################################################
check_if_verbose_requested $1;
initialize;
declare_alias_less;
declare_git_friendly_PS1;
customize_git;
customize_man;
customize_ls;
customize_bash;
customize_bash_history;
other_verbose_processing;

#TODO: If shell level (SHLVL) > 1 then inform (mention in the prompt, or one time at the start)


#######################################################
# Unset helper functions
#######################################################
unset check_if_verbose_requested;
unset initialize
unset declare_alias_less;
unset declare_git_friendly_PS1;
unset customize_git;
unset customize_man;
unset customize_ls;
unset customize_bash;
unset customize_bash_history;
unset other_verbose_processing;

#######################################################
# Unset global variables
#######################################################
unset is_verbose;